#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5F1B2A0789F12B11 (jeremie.galarneau@gmail.com)
#
Name     : lttng-tools
Version  : 2.10.7
Release  : 1
URL      : http://lttng.org/files/lttng-tools/lttng-tools-2.10.7.tar.bz2
Source0  : http://lttng.org/files/lttng-tools/lttng-tools-2.10.7.tar.bz2
Source1 : http://lttng.org/files/lttng-tools/lttng-tools-2.10.7.tar.bz2.asc
Summary  : The LTTng control and utility library is a library used to control the tracing sessions of a LTTng-session daemon
Group    : Development/Tools
License  : LGPL-2.1
Requires: lttng-tools-bin = %{version}-%{release}
Requires: lttng-tools-data = %{version}-%{release}
Requires: lttng-tools-lib = %{version}-%{release}
Requires: lttng-tools-license = %{version}-%{release}
Requires: lttng-tools-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : bison
BuildRequires : flex
BuildRequires : grep
BuildRequires : pkgconfig(liburcu)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(lttng-ust)
BuildRequires : pkgconfig(popt)
BuildRequires : pkgconfig(uuid)
BuildRequires : python-core
BuildRequires : sed
BuildRequires : util-linux-dev
BuildRequires : xmlto
Patch1: 0001-Don-t-use-tid.h-compat-it-s-broken.patch

%description
LTTng core dump snapshot handler
Christian Babeux, June 2013
This is a custom core dump program that will be called when a core dump
occurs. The program will save the core data in CORE_PATH and also, if a
root session daemon is running, will record a snapshot of tracing data
using the lttng command line utility.

%package bin
Summary: bin components for the lttng-tools package.
Group: Binaries
Requires: lttng-tools-data = %{version}-%{release}
Requires: lttng-tools-license = %{version}-%{release}

%description bin
bin components for the lttng-tools package.


%package data
Summary: data components for the lttng-tools package.
Group: Data

%description data
data components for the lttng-tools package.


%package dev
Summary: dev components for the lttng-tools package.
Group: Development
Requires: lttng-tools-lib = %{version}-%{release}
Requires: lttng-tools-bin = %{version}-%{release}
Requires: lttng-tools-data = %{version}-%{release}
Provides: lttng-tools-devel = %{version}-%{release}
Requires: lttng-tools = %{version}-%{release}

%description dev
dev components for the lttng-tools package.


%package doc
Summary: doc components for the lttng-tools package.
Group: Documentation
Requires: lttng-tools-man = %{version}-%{release}

%description doc
doc components for the lttng-tools package.


%package lib
Summary: lib components for the lttng-tools package.
Group: Libraries
Requires: lttng-tools-data = %{version}-%{release}
Requires: lttng-tools-license = %{version}-%{release}

%description lib
lib components for the lttng-tools package.


%package license
Summary: license components for the lttng-tools package.
Group: Default

%description license
license components for the lttng-tools package.


%package man
Summary: man components for the lttng-tools package.
Group: Default

%description man
man components for the lttng-tools package.


%prep
%setup -q -n lttng-tools-2.10.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569522065
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1569522065
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lttng-tools
cp LICENSE %{buildroot}/usr/share/package-licenses/lttng-tools/LICENSE
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/lttng/libexec/lttng-consumerd

%files bin
%defattr(-,root,root,-)
/usr/bin/lttng
/usr/bin/lttng-crash
/usr/bin/lttng-relayd
/usr/bin/lttng-sessiond

%files data
%defattr(-,root,root,-)
/usr/share/xml/lttng/session.xsd

%files dev
%defattr(-,root,root,-)
/usr/include/lttng/action/action.h
/usr/include/lttng/action/notify.h
/usr/include/lttng/channel.h
/usr/include/lttng/condition/buffer-usage.h
/usr/include/lttng/condition/condition.h
/usr/include/lttng/condition/evaluation.h
/usr/include/lttng/constant.h
/usr/include/lttng/domain.h
/usr/include/lttng/endpoint.h
/usr/include/lttng/event.h
/usr/include/lttng/handle.h
/usr/include/lttng/health.h
/usr/include/lttng/load.h
/usr/include/lttng/lttng-error.h
/usr/include/lttng/lttng.h
/usr/include/lttng/notification/channel.h
/usr/include/lttng/notification/notification.h
/usr/include/lttng/save.h
/usr/include/lttng/session.h
/usr/include/lttng/snapshot.h
/usr/include/lttng/trigger/trigger.h
/usr/include/lttng/version.h.tmpl
/usr/lib64/liblttng-ctl.so
/usr/lib64/pkgconfig/lttng-ctl.pc
/usr/share/man/man3/lttng-health-check.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/lttng\-tools/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblttng-ctl.so.0
/usr/lib64/liblttng-ctl.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lttng-tools/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lttng-add-context.1
/usr/share/man/man1/lttng-crash.1
/usr/share/man/man1/lttng-create.1
/usr/share/man/man1/lttng-destroy.1
/usr/share/man/man1/lttng-disable-channel.1
/usr/share/man/man1/lttng-disable-event.1
/usr/share/man/man1/lttng-enable-channel.1
/usr/share/man/man1/lttng-enable-event.1
/usr/share/man/man1/lttng-help.1
/usr/share/man/man1/lttng-list.1
/usr/share/man/man1/lttng-load.1
/usr/share/man/man1/lttng-metadata.1
/usr/share/man/man1/lttng-regenerate.1
/usr/share/man/man1/lttng-save.1
/usr/share/man/man1/lttng-set-session.1
/usr/share/man/man1/lttng-snapshot.1
/usr/share/man/man1/lttng-start.1
/usr/share/man/man1/lttng-status.1
/usr/share/man/man1/lttng-stop.1
/usr/share/man/man1/lttng-track.1
/usr/share/man/man1/lttng-untrack.1
/usr/share/man/man1/lttng-version.1
/usr/share/man/man1/lttng-view.1
/usr/share/man/man1/lttng.1
/usr/share/man/man8/lttng-relayd.8
/usr/share/man/man8/lttng-sessiond.8
