#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: da8b975
#
# Source0 file verified with key 0x5F1B2A0789F12B11 (jeremie.galarneau@gmail.com)
#
Name     : lttng-tools
Version  : 2.12.14
Release  : 19
URL      : http://lttng.org/files/lttng-tools/lttng-tools-2.12.14.tar.bz2
Source0  : http://lttng.org/files/lttng-tools/lttng-tools-2.12.14.tar.bz2
Source1  : http://lttng.org/files/lttng-tools/lttng-tools-2.12.14.tar.bz2.asc
Summary  : The LTTng control and utility library is a library used to control the tracing sessions of a LTTng-session daemon
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: lttng-tools-bin = %{version}-%{release}
Requires: lttng-tools-data = %{version}-%{release}
Requires: lttng-tools-lib = %{version}-%{release}
Requires: lttng-tools-license = %{version}-%{release}
Requires: lttng-tools-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : grep
BuildRequires : pkgconfig(liburcu)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(lttng-ust)
BuildRequires : pkgconfig(popt)
BuildRequires : sed
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
LTTng core dump snapshot handler
Christian Babeux, June 2013
This is a custom core dump program that will be called when a core dump
occurs. The program will save the core data in CORE_PATH and also, if a
root session daemon is running, will record a snapshot of tracing data
using the lttng command line utility.

%package bin
Summary: bin components for the lttng-tools package.
Group: Binaries
Requires: lttng-tools-data = %{version}-%{release}
Requires: lttng-tools-license = %{version}-%{release}

%description bin
bin components for the lttng-tools package.


%package data
Summary: data components for the lttng-tools package.
Group: Data

%description data
data components for the lttng-tools package.


%package dev
Summary: dev components for the lttng-tools package.
Group: Development
Requires: lttng-tools-lib = %{version}-%{release}
Requires: lttng-tools-bin = %{version}-%{release}
Requires: lttng-tools-data = %{version}-%{release}
Provides: lttng-tools-devel = %{version}-%{release}
Requires: lttng-tools = %{version}-%{release}

%description dev
dev components for the lttng-tools package.


%package doc
Summary: doc components for the lttng-tools package.
Group: Documentation
Requires: lttng-tools-man = %{version}-%{release}

%description doc
doc components for the lttng-tools package.


%package lib
Summary: lib components for the lttng-tools package.
Group: Libraries
Requires: lttng-tools-data = %{version}-%{release}
Requires: lttng-tools-license = %{version}-%{release}

%description lib
lib components for the lttng-tools package.


%package license
Summary: license components for the lttng-tools package.
Group: Default

%description license
license components for the lttng-tools package.


%package man
Summary: man components for the lttng-tools package.
Group: Default

%description man
man components for the lttng-tools package.


%prep
%setup -q -n lttng-tools-2.12.14
cd %{_builddir}/lttng-tools-2.12.14
pushd ..
cp -a lttng-tools-2.12.14 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708649408
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1708649408
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lttng-tools
cp %{_builddir}/lttng-tools-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/lttng-tools/f717cf0eeaf3ba3bda0570e996bcb5d73fb5d856 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/lttng/libexec/lttng-consumerd
/usr/lib64/lttng/libexec/lttng-consumerd

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/lttng
/V3/usr/bin/lttng-crash
/V3/usr/bin/lttng-relayd
/V3/usr/bin/lttng-sessiond
/usr/bin/lttng
/usr/bin/lttng-crash
/usr/bin/lttng-relayd
/usr/bin/lttng-sessiond

%files data
%defattr(-,root,root,-)
/usr/share/xml/lttng/session.xsd

%files dev
%defattr(-,root,root,-)
/usr/include/lttng/action/action.h
/usr/include/lttng/action/notify.h
/usr/include/lttng/channel.h
/usr/include/lttng/clear-handle.h
/usr/include/lttng/clear.h
/usr/include/lttng/condition/buffer-usage.h
/usr/include/lttng/condition/condition.h
/usr/include/lttng/condition/evaluation.h
/usr/include/lttng/condition/session-consumed-size.h
/usr/include/lttng/condition/session-rotation.h
/usr/include/lttng/constant.h
/usr/include/lttng/destruction-handle.h
/usr/include/lttng/domain.h
/usr/include/lttng/endpoint.h
/usr/include/lttng/event.h
/usr/include/lttng/handle.h
/usr/include/lttng/health.h
/usr/include/lttng/load.h
/usr/include/lttng/location.h
/usr/include/lttng/lttng-error.h
/usr/include/lttng/lttng.h
/usr/include/lttng/notification/channel.h
/usr/include/lttng/notification/notification.h
/usr/include/lttng/rotation.h
/usr/include/lttng/save.h
/usr/include/lttng/session-descriptor.h
/usr/include/lttng/session.h
/usr/include/lttng/snapshot.h
/usr/include/lttng/tracker.h
/usr/include/lttng/trigger/trigger.h
/usr/include/lttng/userspace-probe.h
/usr/lib64/liblttng-ctl.so
/usr/lib64/pkgconfig/lttng-ctl.pc
/usr/share/man/man3/lttng-health-check.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lttng\-tools/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/liblttng-ctl.so.0.0.0
/usr/lib64/liblttng-ctl.so.0
/usr/lib64/liblttng-ctl.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lttng-tools/f717cf0eeaf3ba3bda0570e996bcb5d73fb5d856

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lttng-add-context.1
/usr/share/man/man1/lttng-clear.1
/usr/share/man/man1/lttng-crash.1
/usr/share/man/man1/lttng-create.1
/usr/share/man/man1/lttng-destroy.1
/usr/share/man/man1/lttng-disable-channel.1
/usr/share/man/man1/lttng-disable-event.1
/usr/share/man/man1/lttng-disable-rotation.1
/usr/share/man/man1/lttng-enable-channel.1
/usr/share/man/man1/lttng-enable-event.1
/usr/share/man/man1/lttng-enable-rotation.1
/usr/share/man/man1/lttng-help.1
/usr/share/man/man1/lttng-list.1
/usr/share/man/man1/lttng-load.1
/usr/share/man/man1/lttng-metadata.1
/usr/share/man/man1/lttng-regenerate.1
/usr/share/man/man1/lttng-rotate.1
/usr/share/man/man1/lttng-save.1
/usr/share/man/man1/lttng-set-session.1
/usr/share/man/man1/lttng-snapshot.1
/usr/share/man/man1/lttng-start.1
/usr/share/man/man1/lttng-status.1
/usr/share/man/man1/lttng-stop.1
/usr/share/man/man1/lttng-track.1
/usr/share/man/man1/lttng-untrack.1
/usr/share/man/man1/lttng-version.1
/usr/share/man/man1/lttng-view.1
/usr/share/man/man1/lttng.1
/usr/share/man/man8/lttng-relayd.8
/usr/share/man/man8/lttng-sessiond.8
